AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  API for generating QR codes

Resources:
  Function:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: "."
      Handler: qrcode
      Runtime: provided.al2023
      Architectures: [arm64]
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            ApiId: !Ref QrApi

  QrApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Description: API for generating QR codes
      Domain:
        CertificateArn: !Ref Certificate
        DomainName: "qr.shogo82148.com"

  RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: "shogo82148.com."
      Name: "qr.shogo82148.com"
      Type: A
      AliasTarget:
        DNSName: !GetAtt ApiGatewayDomainNameV28a799e83c9.RegionalDomainName
        HostedZoneId: !GetAtt ApiGatewayDomainNameV28a799e83c9.RegionalHostedZoneId

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: "qr.shogo82148.com"
      ValidationMethod: "DNS"
      DomainValidationOptions:
        - DomainName: "qr.shogo82148.com"
          HostedZoneId: Z1TR8BQNS8S1I7
